version: '2'

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5
    ports:
      - "2181:2181"
    networks:
      ovocepnet:
        ipv4_address: 172.18.0.2
  kafka:
    container_name: kafka-lippo-broker
    image: rewreu/lo:kafka
    ports:
      - "9092:9092"
    networks:
      ovocepnet:
        ipv4_address: 172.18.0.3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  ovocepnet:
    driver: bridge
    ipam:    
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

